- name: reload systemd service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: restart kokkan timer
  ansible.builtin.systemd_service:
    name: kokkan.timer
    state: restarted

- name: restart loki service
  ansible.builtin.systemd_service:
    name: loki.service
    state: restarted

- name: restart promtail service
  ansible.builtin.systemd_service:
    name: promtail.service
    state: restarted