all:
  vars:
    ansible_user: ansible

  children:
    webservers:
      hosts:
        websrv01:
          ansible_host: 192.168.x.xxx
        websrv02:
          ansible_host: 192.168.x.xxx
        websrv03:
          ansible_host: 192.168.x.xxx

    databases:
      hosts:
        db01:
          ansible_host: 192.168.x.xxx
        db02:
          ansible_host: 192.168.x.xxx
        db03:
          ansible_host: 192.168.x.xxx